### ISSUE TITLE
Does not backup some important folders (e.g. /home and /var)

### ISSUE THREAD

**Issue by kevindd992002** [helmuthb/rsnapshot-docker#2]
So I'm trying to setup and use your container and here's how I have it setup in my docker-compose.yml file:

```
rsnapshot:
    image: helmuthb/rsnapshot
    container_name: rsnapshot
    volumes:
      - /mnt/storage/backup:/backup
      - /:/data
      - /home/kevin/appdata/rsnapshot/backup.cfg:/backup.cfg
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=${PGID}
      - TZ=Asia/Manila
```

A couple of questions/concerns:
1. Is the PUID environment variable necessary to be set to 0 (root) so that it will have all permissions to the whole local filesystem?
2. I tried running "docker exec -it rsnapshot rsnapshot daily" and it did backup most of the folders in my local root filesystem but the /home and /var folder do not have any contents at all. Why is this? I checked the rsnapshot.conf file insider the container and it had these:
```

config_version  1.2
snapshot_root   /backup/
no_create_root  1
cmd_cp          /bin/cp
cmd_rm          /bin/rm
cmd_rsync       /usr/bin/rsync
cmd_ssh         /usr/bin/ssh
ssh_args        -i /ssh-id -o StrictHostKeychecking=no
verbose         1
lockfile        /var/run/rsnapshot.pid
backup          /data   localhost/      one_fs=1
retain  daily   3
retain  weekly  3
retain  monthly 3
retain  yearly  3
```

So it looks like everything is setup correctly. I even checked the contents of /data from inside the container and everything was there.
`

**Comment by kevindd992002** [comment]
Nevermind, I got it solved by specifiying one_fs=1 and excluding /mnt altogether. Now my rsnapshot.conf looks like this:

```
config_version  1.2
snapshot_root   /backup/
no_create_root  1
cmd_cp          /bin/cp
cmd_rm          /bin/rm
cmd_rsync       /usr/bin/rsync
cmd_ssh         /usr/bin/ssh
ssh_args        -i /ssh-id -o StrictHostKeychecking=no
verbose         1
lockfile        /var/run/rsnapshot.pid
backup          /rootfs epsilon/        exclude=/rootfs/mnt
retain  daily   3
retain  weekly  3
retain  monthly 3
retain  yearly  3
```

And my yml file like this:

```
rsnapshot:
    image: helmuthb/rsnapshot
    container_name: rsnapshot
    volumes:
      - /mnt/storage/backup:/backup
      - /:/rootfs
      - /home/kevin/appdata/rsnapshot/backup.cfg:/backup.cfg
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Manila
      - BACKUP_NAME=epsilon
      - BACKUP_SOURCE=/rootfs
      - BACKUP_OPTS=one_fs=0
      - BACKUP_OPTS=exclude=/rootfs/mnt
```

My problem now though is that when I run `docker exec -it rsnapshot rsnapshot daily` from the host, it never finishes but when I check the target folder for the backup everyting seems to be backed up properly. Your container also isn't set to do logging so I don't know what to check to troubleshoot the issue. Can you please help?
